### Site Settings ###
title: Akash Sharma
description: >- # >- means to ignore newlines until "url:"
  Education never ends, Watson. It is a series of lessons, with the greatest for the last.

url: "" # base hostname & protocol for your site (e.g. http://example.com)
baseurl: "" # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository: asrma2/asrma2.github.io # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
# remote_theme       : YoussefRaafatNasry/portfolYOU    # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name: Akash Sharma
  image: images/l2.png
#  behance: asrma2
  # dribbble          : your_username
  email: asrma2@gmail.com
  # facebook          : your_username
  github: asrma2
  # gitlab            : your_username
  # instagram         : your_username
  linkedin: akash-sharma-82605a119
  medium: asrma2
  # soundcloud        : your_username
#  spotify: 4B2cRJSLnH3XKLHh7VehXC
  # stackoverflow     : your_user_id
  # tumblr            : your_username.tumblr.com
  # twitch            : your_username
  twitter: asrma1997
# vimeo             : your_username
# youtube           : your_channel_name

### Pagination ###
paginate: 6
paginate_path: "/articles/page-:num/"

### Posts Permalink ###
permalink: articles/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor/
